# --- COMA specific parameters ---

action_selector: "gumbel"
epsilon_start: .5
epsilon_finish: .01
epsilon_anneal_time: 4000
mask_before_softmax: True # set to True for entropy regularization

runner: "parallel"

buffer_size: 8
batch_size_run: 8
batch_size: 8

td_lambda: 0.8


# update the target network every {} training episode
target_update_interval: 32

# use lica
agent_output_type: "pi_logits"
learner: "lica_learner"
mixing_embed_dim: 64
hypernet_layers: 2
critics_update_num: 1 # legacy hyperparameter, will be removed
entropy_coef: 0.11 # 0.03 for 3s5z_vs_3s6z, 0.06 for all others 0.1,0.2

name: "lica"
